# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3d887faf950da94eb3c268564a66bf56298cb71ff85004450fc2860ffdbb1c1577266f2f01f266e4b702e9a79f2e23478fd3e387ebd510ffae6db3f16885bf

test:
  secret_key_base: e836f6ac04de3c610a9ae6e2f06de290f140738d5c453ce4d621123e00af6115a89197d6ce0a98a875fae0ad5720213143216312dbe8ac52345d4366f09e5159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
